# eta_combustor (n_combustor) används inte
# delta_h_LPT = (psi_LPC*(u_sum_LPT))
# psi_LPT negativt -> delta_h_LPT negativt -> delta_T_LPT = delta_h_LPT/c_p_7 negativt
# -> T_8 = T_7 - delta_T_LPT ger T_8 > T_7

parameter_list = [
    T_cruise,
    a,
    P_1,
    T_1,
    a_1,
    C_p_1,
    P_2,
    T_2,
    gamma_air_2,
    C_p_2,
    r_hub_fan_nu,
    ratio_hub_fan,
    a_2,
    c_air_fan,
    U_fan,
    omega_fan,
    RPM_fan,
    U_mid_fan,
    sum_U_squared_fan,
    Delta_H_fan,
    Delta_T_fan,
    T_3,
    FPR,
    P_3,
    MFP,
    mass_flow,
    gamma_air_3,
    C_p_3,
    omega_LPC,
    U_mid_LPC,
    sum_U_squared_LPC,
    Delta_H_LPC,
    Delta_T_LPC,
    T_4,
    LPC_PR,
    P_4,
    gamma_air_4,
    C_p_4,
    a_4,
    c_air_HPC,
    U_HPC,
    omega_HPC,
    RPM_HPC,
    U_mid_HPC,
    sum_U_squared_HPC,
    Delta_h_HPC,
    Delta_T_HPC,
    T_5,
    HPC_PR,
    P_5,
    gamma_air_5,
    C_p_5,
    C_p_mixed_5,
    gamma_mixed_5,
    Delta_H_combustion,
    P_6,
    omega_HPT,
    gamma_mixed_6,
    C_p_6,
    U_HPT,
    sum_U_squared_HPT,
    Delta_H_HPT,
    Delta_T_HPT,
    T_6,
    T_7,
    HPT_PR,
    P_7,
    C_p_7,
    gamma_mixed_7,
    omega_LPT,
    U_mid_LPT,
    sum_U_squared_LPT,
    Delta_H_LPT,
    Delta_T_LPT,
    T_8,
    LPT_PR,
    P_8,
    r_ratio_BPR,
    BPR
]

name_list = [

]

values = [(name_list[item], parameter_list[item]) for item in range(len(parameter_list))]
for i in range(len(values)):
    print('\n')
    print(values[i])
